# Generated by Django 4.2.2 on 2024-09-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name2', models.CharField(max_length=200)),
                ('Email2', models.EmailField(max_length=254)),
                ('Phone2', models.CharField(max_length=200)),
                ('Product2', models.CharField(max_length=200)),
                ('Message2', models.TextField()),
            ],
        ),
    ]
